logger:
  local_dir: ${platform.path_exps}
  use_wandb: true
  wandb_project_name: NeMo
credentials:
  kaggle:
    username: '...'
    key: '...'
  opendatalab:
    username: '...'
    password: '...'
platform:
  link: slurm
  shared_home_with_local: false
  restart_upon_fail: true
  ws_name: od3d
  pull_od3d: true
  pull_od3d_submodules: true
  install_od3d: true
  path_od3d: /work/dlclarge1/sommerl-od3d/common3d
  path_datasets_raw: /work/dlclarge1/sommerl-od3d/datasets
  path_datasets_preprocess: /work/dlclarge1/sommerl-od3d/datasets
  path_exps: /work/dlclarge1/sommerl-od3d/exps
  path_cuda: /usr/local/cuda-12.4
  path_home: /work/dlclarge2/mathurv-mathurv-cv1project/common3d/home
  url_od3d: git@github.com:GenIntel/common3d.git
  partition: dllabdlc_gpu-rtx2080
  username: sommerl
  gpu_count: 1
  cpu_count: 8
  ram: 40gb
  walltime: '24:00:00'
  renderer: pytorch3d
platform_local:
  link: slurm
  shared_home_with_local: false
  restart_upon_fail: true
  ws_name: od3d
  pull_od3d: true
  pull_od3d_submodules: true
  install_od3d: true
  path_od3d: /work/dlclarge1/sommerl-od3d/common3d
  path_datasets_raw: /work/dlclarge1/sommerl-od3d/datasets
  path_datasets_preprocess: /work/dlclarge1/sommerl-od3d/datasets
  path_exps: /work/dlclarge1/sommerl-od3d/exps
  path_cuda: /usr/local/cuda-12.4
  path_home: /work/dlclarge2/mathurv-mathurv-cv1project/common3d/home
  url_od3d: git@github.com:GenIntel/common3d.git
  partition: dllabdlc_gpu-rtx2080
  username: sommerl
  gpu_count: 1
  cpu_count: 8
  ram: 40gb
  walltime: '24:00:00'
  renderer: pytorch3d
use_wandb: true
wandb_project_name: NeMo
seed_number: 0
training:
  scale_iterations_per_epoch: 1.0
inference:
  visualize_num_samples: 0
branch: main
